-- ISO 3166-1 country names
-- courtesy http://www.iso.org/iso/country_codes/iso_3166_code_lists.htm
insert into Country values ( 'AF' , 'AFGHANISTAN' );
insert into Country values ( 'AX ÅLAND' , 'ISLANDS' );
insert into Country values ( 'AL' , 'ALBANIA' );
insert into Country values ( 'DZ' , 'ALGERIA' );
insert into Country values ( 'AS AMERICAN' , 'SAMOA' );
insert into Country values ( 'AD' , 'ANDORRA' );
insert into Country values ( 'AO' , 'ANGOLA' );
insert into Country values ( 'AI' , 'ANGUILLA' );
insert into Country values ( 'AQ' , 'ANTARCTICA' );
insert into Country values ( 'AG ANTIGUA AND' , 'BARBUDA' );
insert into Country values ( 'AR' , 'ARGENTINA' );
insert into Country values ( 'AM' , 'ARMENIA' );
insert into Country values ( 'AW' , 'ARUBA' );
insert into Country values ( 'AU' , 'AUSTRALIA' );
insert into Country values ( 'AT' , 'AUSTRIA' );
insert into Country values ( 'AZ' , 'AZERBAIJAN' );
insert into Country values ( 'BS' , 'BAHAMAS' );
insert into Country values ( 'BH' , 'BAHRAIN' );
insert into Country values ( 'BD' , 'BANGLADESH' );
insert into Country values ( 'BB' , 'BARBADOS' );
insert into Country values ( 'BY' , 'BELARUS' );
insert into Country values ( 'BE' , 'BELGIUM' );
insert into Country values ( 'BZ' , 'BELIZE' );
insert into Country values ( 'BJ' , 'BENIN' );
insert into Country values ( 'BM' , 'BERMUDA' );
insert into Country values ( 'BT' , 'BHUTAN' );
insert into Country values ( 'BO BOLIVIA, PLURINATIONAL STATE' , 'OF' );
insert into Country values ( 'BQ BONAIRE, SINT EUSTATIUS AND' , 'SABA' );
insert into Country values ( 'BA BOSNIA AND' , 'HERZEGOVINA' );
insert into Country values ( 'BW' , 'BOTSWANA' );
insert into Country values ( 'BV BOUVET' , 'ISLAND' );
insert into Country values ( 'BR' , 'BRAZIL' );
insert into Country values ( 'IO BRITISH INDIAN OCEAN' , 'TERRITORY' );
insert into Country values ( 'BN BRUNEI' , 'DARUSSALAM' );
insert into Country values ( 'BG' , 'BULGARIA' );
insert into Country values ( 'BF BURKINA' , 'FASO' );
insert into Country values ( 'BI' , 'BURUNDI' );
insert into Country values ( 'KH' , 'CAMBODIA' );
insert into Country values ( 'CM' , 'CAMEROON' );
insert into Country values ( 'CA' , 'CANADA' );
insert into Country values ( 'CV CAPE' , 'VERDE' );
insert into Country values ( 'KY CAYMAN' , 'ISLANDS' );
insert into Country values ( 'CF CENTRAL AFRICAN' , 'REPUBLIC' );
insert into Country values ( 'TD' , 'CHAD' );
insert into Country values ( 'CL' , 'CHILE' );
insert into Country values ( 'CN' , 'CHINA' );
insert into Country values ( 'CX CHRISTMAS' , 'ISLAND' );
insert into Country values ( 'CC COCOS (KEELING)' , 'ISLANDS' );
insert into Country values ( 'CO' , 'COLOMBIA' );
insert into Country values ( 'KM' , 'COMOROS' );
insert into Country values ( 'CG' , 'CONGO' );
insert into Country values ( 'CD CONGO, THE DEMOCRATIC REPUBLIC OF' , 'THE' );
insert into Country values ( 'CK COOK' , 'ISLANDS' );
insert into Country values ( 'CR COSTA' , 'RICA' );
insert into Country values ( 'CI CÔTE' , 'D'IVOIRE' );
insert into Country values ( 'HR' , 'CROATIA' );
insert into Country values ( 'CU' , 'CUBA' );
insert into Country values ( 'CW' , 'CURAÇAO' );
insert into Country values ( 'CY' , 'CYPRUS' );
insert into Country values ( 'CZ CZECH' , 'REPUBLIC' );
insert into Country values ( 'DK' , 'DENMARK' );
insert into Country values ( 'DJ' , 'DJIBOUTI' );
insert into Country values ( 'DM' , 'DOMINICA' );
insert into Country values ( 'DO DOMINICAN' , 'REPUBLIC' );
insert into Country values ( 'EC' , 'ECUADOR' );
insert into Country values ( 'EG' , 'EGYPT' );
insert into Country values ( 'SV EL' , 'SALVADOR' );
insert into Country values ( 'GQ EQUATORIAL' , 'GUINEA' );
insert into Country values ( 'ER' , 'ERITREA' );
insert into Country values ( 'EE' , 'ESTONIA' );
insert into Country values ( 'ET' , 'ETHIOPIA' );
insert into Country values ( 'FK FALKLAND ISLANDS' , '(MALVINAS)' );
insert into Country values ( 'FO FAROE' , 'ISLANDS' );
insert into Country values ( 'FJ' , 'FIJI' );
insert into Country values ( 'FI' , 'FINLAND' );
insert into Country values ( 'FR' , 'FRANCE' );
insert into Country values ( 'GF FRENCH' , 'GUIANA' );
insert into Country values ( 'PF FRENCH' , 'POLYNESIA' );
insert into Country values ( 'TF FRENCH SOUTHERN' , 'TERRITORIES' );
insert into Country values ( 'GA' , 'GABON' );
insert into Country values ( 'GM' , 'GAMBIA' );
insert into Country values ( 'GE' , 'GEORGIA' );
insert into Country values ( 'DE' , 'GERMANY' );
insert into Country values ( 'GH' , 'GHANA' );
insert into Country values ( 'GI' , 'GIBRALTAR' );
insert into Country values ( 'GR' , 'GREECE' );
insert into Country values ( 'GL' , 'GREENLAND' );
insert into Country values ( 'GD' , 'GRENADA' );
insert into Country values ( 'GP' , 'GUADELOUPE' );
insert into Country values ( 'GU' , 'GUAM' );
insert into Country values ( 'GT' , 'GUATEMALA' );
insert into Country values ( 'GG' , 'GUERNSEY' );
insert into Country values ( 'GN' , 'GUINEA' );
insert into Country values ( 'GW' , 'GUINEA-BISSAU' );
insert into Country values ( 'GY' , 'GUYANA' );
insert into Country values ( 'HT' , 'HAITI' );
insert into Country values ( 'HM HEARD ISLAND AND MCDONALD' , 'ISLANDS' );
insert into Country values ( 'VA HOLY SEE (VATICAN CITY' , 'STATE)' );
insert into Country values ( 'HN' , 'HONDURAS' );
insert into Country values ( 'HK HONG' , 'KONG' );
insert into Country values ( 'HU' , 'HUNGARY' );
insert into Country values ( 'IS' , 'ICELAND' );
insert into Country values ( 'IN' , 'INDIA' );
insert into Country values ( 'ID' , 'INDONESIA' );
insert into Country values ( 'IR IRAN, ISLAMIC REPUBLIC' , 'OF' );
insert into Country values ( 'IQ' , 'IRAQ' );
insert into Country values ( 'IE' , 'IRELAND' );
insert into Country values ( 'IM ISLE OF' , 'MAN' );
insert into Country values ( 'IL' , 'ISRAEL' );
insert into Country values ( 'IT' , 'ITALY' );
insert into Country values ( 'JM' , 'JAMAICA' );
insert into Country values ( 'JP' , 'JAPAN' );
insert into Country values ( 'JE' , 'JERSEY' );
insert into Country values ( 'JO' , 'JORDAN' );
insert into Country values ( 'KZ' , 'KAZAKHSTAN' );
insert into Country values ( 'KE' , 'KENYA' );
insert into Country values ( 'KI' , 'KIRIBATI' );
insert into Country values ( 'KP KOREA, DEMOCRATIC PEOPLE'S REPUBLIC' , 'OF' );
insert into Country values ( 'KR KOREA, REPUBLIC' , 'OF' );
insert into Country values ( 'KW' , 'KUWAIT' );
insert into Country values ( 'KG' , 'KYRGYZSTAN' );
insert into Country values ( 'LA LAO PEOPLE'S DEMOCRATIC' , 'REPUBLIC' );
insert into Country values ( 'LV' , 'LATVIA' );
insert into Country values ( 'LB' , 'LEBANON' );
insert into Country values ( 'LS' , 'LESOTHO' );
insert into Country values ( 'LR' , 'LIBERIA' );
insert into Country values ( 'LY' , 'LIBYA' );
insert into Country values ( 'LI' , 'LIECHTENSTEIN' );
insert into Country values ( 'LT' , 'LITHUANIA' );
insert into Country values ( 'LU' , 'LUXEMBOURG' );
insert into Country values ( 'MO' , 'MACAO' );
insert into Country values ( 'MK MACEDONIA, THE FORMER YUGOSLAV REPUBLIC' , 'OF' );
insert into Country values ( 'MG' , 'MADAGASCAR' );
insert into Country values ( 'MW' , 'MALAWI' );
insert into Country values ( 'MY' , 'MALAYSIA' );
insert into Country values ( 'MV' , 'MALDIVES' );
insert into Country values ( 'ML' , 'MALI' );
insert into Country values ( 'MT' , 'MALTA' );
insert into Country values ( 'MH MARSHALL' , 'ISLANDS' );
insert into Country values ( 'MQ' , 'MARTINIQUE' );
insert into Country values ( 'MR' , 'MAURITANIA' );
insert into Country values ( 'MU' , 'MAURITIUS' );
insert into Country values ( 'YT' , 'MAYOTTE' );
insert into Country values ( 'MX' , 'MEXICO' );
insert into Country values ( 'FM MICRONESIA, FEDERATED STATES' , 'OF' );
insert into Country values ( 'MD MOLDOVA, REPUBLIC' , 'OF' );
insert into Country values ( 'MC' , 'MONACO' );
insert into Country values ( 'MN' , 'MONGOLIA' );
insert into Country values ( 'ME' , 'MONTENEGRO' );
insert into Country values ( 'MS' , 'MONTSERRAT' );
insert into Country values ( 'MA' , 'MOROCCO' );
insert into Country values ( 'MZ' , 'MOZAMBIQUE' );
insert into Country values ( 'MM' , 'MYANMAR' );
insert into Country values ( 'NA' , 'NAMIBIA' );
insert into Country values ( 'NR' , 'NAURU' );
insert into Country values ( 'NP' , 'NEPAL' );
insert into Country values ( 'NL' , 'NETHERLANDS' );
insert into Country values ( 'NC NEW' , 'CALEDONIA' );
insert into Country values ( 'NZ NEW' , 'ZEALAND' );
insert into Country values ( 'NI' , 'NICARAGUA' );
insert into Country values ( 'NE' , 'NIGER' );
insert into Country values ( 'NG' , 'NIGERIA' );
insert into Country values ( 'NU' , 'NIUE' );
insert into Country values ( 'NF NORFOLK' , 'ISLAND' );
insert into Country values ( 'MP NORTHERN MARIANA' , 'ISLANDS' );
insert into Country values ( 'NO' , 'NORWAY' );
insert into Country values ( 'OM' , 'OMAN' );
insert into Country values ( 'PK' , 'PAKISTAN' );
insert into Country values ( 'PW' , 'PALAU' );
insert into Country values ( 'PS PALESTINIAN TERRITORY,' , 'OCCUPIED' );
insert into Country values ( 'PA' , 'PANAMA' );
insert into Country values ( 'PG PAPUA NEW' , 'GUINEA' );
insert into Country values ( 'PY' , 'PARAGUAY' );
insert into Country values ( 'PE' , 'PERU' );
insert into Country values ( 'PH' , 'PHILIPPINES' );
insert into Country values ( 'PN' , 'PITCAIRN' );
insert into Country values ( 'PL' , 'POLAND' );
insert into Country values ( 'PT' , 'PORTUGAL' );
insert into Country values ( 'PR PUERTO' , 'RICO' );
insert into Country values ( 'QA' , 'QATAR' );
insert into Country values ( 'RE' , 'RÉUNION' );
insert into Country values ( 'RO' , 'ROMANIA' );
insert into Country values ( 'RU RUSSIAN' , 'FEDERATION' );
insert into Country values ( 'RW' , 'RWANDA' );
insert into Country values ( 'BL SAINT' , 'BARTHÉLEMY' );
insert into Country values ( 'SH SAINT HELENA, ASCENSION AND TRISTAN DA' , 'CUNHA' );
insert into Country values ( 'KN SAINT KITTS AND' , 'NEVIS' );
insert into Country values ( 'LC SAINT' , 'LUCIA' );
insert into Country values ( 'MF SAINT MARTIN (FRENCH' , 'PART)' );
insert into Country values ( 'PM SAINT PIERRE AND' , 'MIQUELON' );
insert into Country values ( 'VC SAINT VINCENT AND THE' , 'GRENADINES' );
insert into Country values ( 'WS' , 'SAMOA' );
insert into Country values ( 'SM SAN' , 'MARINO' );
insert into Country values ( 'ST SAO TOME AND' , 'PRINCIPE' );
insert into Country values ( 'SA SAUDI' , 'ARABIA' );
insert into Country values ( 'SN' , 'SENEGAL' );
insert into Country values ( 'RS' , 'SERBIA' );
insert into Country values ( 'SC' , 'SEYCHELLES' );
insert into Country values ( 'SL SIERRA' , 'LEONE' );
insert into Country values ( 'SG' , 'SINGAPORE' );
insert into Country values ( 'SX SINT MAARTEN (DUTCH' , 'PART)' );
insert into Country values ( 'SK' , 'SLOVAKIA' );
insert into Country values ( 'SI' , 'SLOVENIA' );
insert into Country values ( 'SB SOLOMON' , 'ISLANDS' );
insert into Country values ( 'SO' , 'SOMALIA' );
insert into Country values ( 'ZA SOUTH' , 'AFRICA' );
insert into Country values ( 'GS SOUTH GEORGIA AND THE SOUTH SANDWICH' , 'ISLANDS' );
insert into Country values ( 'SS SOUTH' , 'SUDAN' );
insert into Country values ( 'ES' , 'SPAIN' );
insert into Country values ( 'LK SRI' , 'LANKA' );
insert into Country values ( 'SD' , 'SUDAN' );
insert into Country values ( 'SR' , 'SURINAME' );
insert into Country values ( 'SJ SVALBARD AND JAN' , 'MAYEN' );
insert into Country values ( 'SZ' , 'SWAZILAND' );
insert into Country values ( 'SE' , 'SWEDEN' );
insert into Country values ( 'CH' , 'SWITZERLAND' );
insert into Country values ( 'SY SYRIAN ARAB' , 'REPUBLIC' );
insert into Country values ( 'TW TAIWAN, PROVINCE OF' , 'CHINA' );
insert into Country values ( 'TJ' , 'TAJIKISTAN' );
insert into Country values ( 'TZ TANZANIA, UNITED REPUBLIC' , 'OF' );
insert into Country values ( 'TH' , 'THAILAND' );
insert into Country values ( 'TL' , 'TIMOR-LESTE' );
insert into Country values ( 'TG' , 'TOGO' );
insert into Country values ( 'TK' , 'TOKELAU' );
insert into Country values ( 'TO' , 'TONGA' );
insert into Country values ( 'TT TRINIDAD AND' , 'TOBAGO' );
insert into Country values ( 'TN' , 'TUNISIA' );
insert into Country values ( 'TR' , 'TURKEY' );
insert into Country values ( 'TM' , 'TURKMENISTAN' );
insert into Country values ( 'TC TURKS AND CAICOS' , 'ISLANDS' );
insert into Country values ( 'TV' , 'TUVALU' );
insert into Country values ( 'UG' , 'UGANDA' );
insert into Country values ( 'UA' , 'UKRAINE' );
insert into Country values ( 'AE UNITED ARAB' , 'EMIRATES' );
insert into Country values ( 'GB UNITED' , 'KINGDOM' );
insert into Country values ( 'US UNITED' , 'STATES' );
insert into Country values ( 'UM UNITED STATES MINOR OUTLYING' , 'ISLANDS' );
insert into Country values ( 'UY' , 'URUGUAY' );
insert into Country values ( 'UZ' , 'UZBEKISTAN' );
insert into Country values ( 'VU' , 'VANUATU' );
insert into Country values ( 'VE VENEZUELA, BOLIVARIAN REPUBLIC' , 'OF' );
insert into Country values ( 'VN VIET' , 'NAM' );
insert into Country values ( 'VG VIRGIN ISLANDS,' , 'BRITISH' );
insert into Country values ( 'VI VIRGIN ISLANDS,' , 'U.S.' );
insert into Country values ( 'WF WALLIS AND' , 'FUTUNA' );
insert into Country values ( 'EH WESTERN' , 'SAHARA' );
insert into Country values ( 'YE' , 'YEMEN' );
insert into Country values ( 'ZM' , 'ZAMBIA' );
insert into Country values ( 'ZW' , 'ZIMBABWE' );